@echo off
echo Removing old images...
docker rm $(docker stop $(docker ps -a -q --filter ancestor=<image-name> --format="{{.ID}}"))
echo Building new version...
docker build -t repository-container .
echo starting container for repository-container...
docker run -d -p 2222:22 docker.io/library/repository-container
echo container repository-container started and listening on port 2222
